language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update --prefer-source --no-interaction

script: ./vendor/bin/phpunit

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: always
